FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json tsconfig.json ./
RUN npm install

# Copy everything (code, prisma, env, etc.)
COPY . .

# Expose port
EXPOSE 8000

RUN npm run build

# Copy entrypoint
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]
# CMD ["npx", "ts-node", "src/index.ts"]